permalink:           pretty

# Setup
title:               Feyza Yavuz
tagline:             ''
description:         Aloha. <img src="https://cdn4.iconfinder.com/data/icons/ibrandify-basic-essentials-icon-set/512/pen_stroke_sketch_doodle_lineart_206-128.png" />
url:                 http://jessebett.com/TorusKnotFibration
baseurl:             ''

# About/contact
author:
  name:              Feyza
  url:               https://twitter.com/feyzayavuzz
  email:             feyzaayavuz@gmail.com

# Custom vars
version:             1.0.0
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"