# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown: kramdown

#relative_permalinks: true

# Setup
title:               Torus Knot Fibration Visualization
tagline:             'by Jesse Bettencourt'
description:         'A Summer Project for my Masters in Mathematics at the Unviersity of Toronto under the supervision of Dr. Dror Bar-Natan'
url:                 'http://jessebett.github.io/'
baseurl:             '/TorusKnotFibration'
#baseurl:              ''
paginate:            1

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

gems: ["jekyll-paginate"]
